baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site by Pablo'
theme = "stack"

[params]
  logo = "images/logo.jpg" 

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/_index"
    weight = 1

  [[menu.main]]
    name = "Markdown"
    url = "/markdown/"
    weight = 2

  [[menu.main]]
    name = "Python"
    url = "/python/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
